site_name: PyFSD

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - content.action.edit
    - content.action.view
  icon:
    logo: logo
   
 
plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://zopeinterface.readthedocs.io/en/latest/objects.inv
          options:
            docstring_style: sphinx
            annotations_path: brief
  - offline

repo_url: https://github.com/gamecss/pyfsd
repo_name: gamecss/pyfsd
edit_uri: edit/early-dev/docs/

nav:
  - 拄曳: index.md
  - 安装: install.md
  - 插件: plugin.md
