site_name: "pyfsd"
site_description: "An implementation of protocol 9 of FSD based on Python & Twisted."
site_url: "https://cfcsim.github.io/pyfsd"
repo_url: "https://github.com/cfcsim/pyfsd"
repo_name: "cfcsim/pyfsd"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/pyfsd]
copyright: Copyright &copy; 2023 gamecss
edit_uri: edit/early-dev/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- 首页:
  - 总览: index.md
  - 更改日志: changelog.md
  - 制作人员: credits.md
  - 开源协议: license.md
  - 贡献指南: contributing.md
  - 行为准则: code_of_conduct.md
- 使用指南:
  - 安装: install.md
  - 插件: plugin.md
  - 配置: configure.md
  - 命令行工具:
    - import_user: cmdline_tools/import_user.md
- 开发指南:
  - 插件: develop/plugin.md
  # defer to gen-files + literate-nav
  - API参考:
    - pyfsd: reference/


theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: true

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://zopeinterface.readthedocs.io/en/latest/objects.inv
        - https://docs.twisted.org/en/stable/api/objects.inv
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          heading_level: 1
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
- git-committers:
    enabled: false
    repository: cfcsim/pyfsd

- minify:
    minify_html: true

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/gamecss
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/pyfsd/
