site_name: PyFSD

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - content.action.edit
  icon:
    logo: logo
   
 
plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - mkdocstrings
  - offline

repo_url: https://github.com/gamecss/pyfsd
repo_name: gamecss/pyfsd

nav:
  - 拄曳: index.md
