# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: "PyFSD"
site_description: "用 Python 写成的 FSD 协议9实现"
site_url: "https://cfcsim.github.io/pyfsd/"
repo_url: "https://github.com/cfcsim/pyfsd"
repo_name: "cfcsim/pyfsd"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/pyfsd]
copyright: Copyright &copy; 2023-2024 tonestory6809
edit_uri: edit/async_dev/docs/

nav:
- 首页:
  - 总览: index.md
  - 更改日志: changelog.md
  - 开源协议: license.md
  - 贡献指南: contributing.md
  - 行为准则: code_of_conduct.md
- 使用指南:
  - 安装: install.md
  - 配置: configure.md
  - 插件: plugin.md
  - 命令行工具:
    - import_user: cmdline_tools/import_user.md
- 开发指南:
  - 插件: develop/plugin.md
  - API参考: develop/api.md


theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: cyan
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue gray
    accent: teal
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- md_in_html
- pymdownx.details
- pymdownx.emoji:
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
- pymdownx.tasklist:
- toc:
    permalink: true

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          find_stubs_package: true
          heading_level: 1
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          show_overloads: true
- minify:
    minify_html: true

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/cfcsim/pyfsd/
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/pyfsd/
  version:
    provider: mike
