[pyfsd.database]
source = "sqlite3"
filename = "pyfsd.db"

[pyfsd.client]
port = 6809
motd = """Shhh... Let's not leak out hard work
Developer: Telegram @gamecss"""
motd_encoding = "ascii"
blacklist = []

[pyfsd.metar]
mode = "cron"
cron_time = 3600
fetchers = ["NOAA"]
