[pyfsd.database]
source = "sqlite3"
filename = "pyfsd.db"

[pyfsd.client]
port = 6810
motd = """Shhh... Let's not leak out hard work
Developer: Telegram @gamecss"""
blacklist = []

[pyfsd.metar]
mode = "once"
fetchers = ["NOAA"]
