[pyfsd]
database_name = "pyfsd.db"

[pyfsd.client]
port = 6810
motd = """Shhh... Let's not leak out hard work
Developer: Telegram @gamecss"""
blacklist = []

[pyfsd.metar]
mode = "cron"
cron_time = 3600
fetchers = ["NOAA"]
