[tool.isort]
profile = "black"

[project]
name = "pyfsd"
version = "0.1.0"
description = ""
authors = [
    {name = "gamecss", email = "52902973+gamecss@users.noreply.github.com"},
]
dependencies = [
    "twisted>=22.10.0",
    "loguru>=0.6.0",
    "haversine>=2.7.0",
    "black>=23.1.0",
    "flake8>=6.0.0",
    "isort>=5.12.0",
    "pylance>=0.3.7",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
