[build-system]
requires = ["pdm-backend", "versioneer[toml]>=0.29" ]
build-backend = "pdm.backend"

[project]
name = "pyfsd"
description = "An implementation of protocol 9 of FSD based on Python."
authors = [{name = "tonestory6809", email = "175278158+tonestory6809@users.noreply.github.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
keywords = []
dynamic = ["version"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Documentation",
    "Typing :: Typed",
]
dependencies = [
    "haversine~=2.9",
    "tomli~=2.2; python_version < \"3.11\"",
    "metar~=1.11",
    "sqlalchemy[asyncio]~=2.0",
    "aiohttp~=3.11",
    "typing-extensions~=4.13",
    "argon2-cffi~=23.1",
    "dependency-injector~=4.46",
    "structlog~=25.2",
    "colorama~=0.4; sys_platform == \"win32\"",
    "better-exceptions~=0.3",
]

[project.urls]
Homepage = "https://github.com/cfcsim/pyfsd"
Documentation = "https://cfcsim.github.io/pyfsd"
Repository = "https://github.com/cfcsim/pyfsd"
Issues = "https://github.com/cfcsim/pyfsd/issues"
Discussions = "https://github.com/cfcsim/pyfsd/discussions"

[project.optional-dependencies]
sqlite3 = [
    "aiosqlite~=0.21",
]
postgresql = [
    "asyncpg~=0.30",
]
mysql = [
    "asyncmy~=0.2",
]
oracle = [
    "oracledb~=3.1",
]
mssql = [
    "aioodbc~=0.5",
]

[tool.pdm.build]
package-dir = "src"
includes = ["src/pyfsd", "src/pyfsd/plugins/__init__.py"]
excludes = ["src/pyfsd/plugins/*", "**/.mypy_cache"]

[tool.pdm.scripts]
start = "python -m pyfsd"

[tool.pdm.version]
source = "call"
getter = "versioneer:get_version"
write_to = "pyfsd/_version.py"
write_template = "version = \"{}\"\n"

[tool.pyright]
exclude = [
    "**/__pycache__",
    "__pypackages__",
    ".venv",
    ".git",
]

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "COM819", "D206", "D300", "E111", "E114", "E117", "EM101", "EM102", "ISC002", "PT", "PTH", "Q000", "Q001", "Q002", "Q003", "TD002", "TD003", "TRY003", "W191"]
fixable = ["ALL"]
exclude = [".venv"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "NONE"
versionfile_build = "NONE"
tag_prefix = ""
parentdir_prefix = "pyfsd-"

[tool.mypy]
namespace_packages = true
exclude = "scripts"
python_version = "3.9"
strict = true
disallow_any_generics = false

[[tool.mypy.overrides]]
module = "haversine"
ignore_missing_imports = true

[dependency-groups]
dev = [
    "mypy~=1.15",
    "ruff~=0.11",
]
docs = [
    "mkdocs-material~=9.6",
    "mkdocstrings[python]~=0.29",
    "mkdocs-minify-plugin~=0.8",
    "markdown-callouts~=0.4",
    "markdown-exec~=1.10",
    "mkdocs~=1.6",
    "mkdocs-gen-files~=0.5",
    "mkdocs-git-committers-plugin-2~=2.5",
    "mkdocs-literate-nav~=0.6",
    "mkdocs-minify-plugin~=0.8",
    "mike~=2.1",
]

