[project]
name = "pyfsd"
version = "0.1.0"
description = ""
authors = [
    {name = "gamecss", email = "52902973+gamecss@users.noreply.github.com"},
]
dependencies = [
    "twisted>=22.10.0",
    "loguru>=0.6.0",
    "haversine>=2.8.0",
    "tomli>=1.1.0; python_version<'3.11'",
    "metar>=1.9.0",
]
requires-python = ">=3.8.1"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.1.0",
    "flake8>=6.0.0",
    "isort>=5.12.0",
    "mypy>=1.3.0",
]

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.isort]
profile = "black"

[tool.pdm.scripts]
start = "twistd -n pyfsd"

[tool.pyright]
exclude = [
    "**/__pycache__",
    "__pypackages__",
    ".venv",
    ".git",
]
