name: Deploy docs

on:
  push:
    branches: ["async_dev"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch gh-pages branch
        run: git fetch --unshallow origin gh-pages || true
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.13
          cache: true
      - name: Install dependencies
        run: pdm install -G docs
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Build & publish
        run: |
          source .venv/bin/activate
          mike deploy --push async_dev && mike set-default --push async_dev
